-- PostgreSQL活用テーブル設計
-- 使用方法: psql -f schema_design.sql

-- 部屋テーブル（JSONB、ENUM、幾何型活用）
CREATE TABLE rooms (
    id SERIAL PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4(),
    name VARCHAR(100) NOT NULL,
    room_type room_type_enum NOT NULL,
    price_per_night DECIMAL(10, 2) NOT NULL,
    max_guests INTEGER NOT NULL,
    
    -- JSONB活用（柔軟なメタデータ）
    amenities JSONB,
    
    -- 幾何データ型（PostGIS無しでも基本的な位置情報）
    location POINT,
    
    -- 範囲型（価格帯）
    price_range_weekday int4range,
    price_range_weekend int4range,
    
    -- 配列型（タグ）
    tags TEXT[],
    
    -- タイムゾーン付きタイムスタンプ
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ゲストテーブル（配列、JSONB活用）
CREATE TABLE guests (
    id SERIAL PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    registration_date DATE NOT NULL,
    guest_type guest_status_enum DEFAULT 'active',
    
    -- 配列型（好み）
    preferences TEXT[],
    
    -- JSONB（プロファイル情報）
    profile JSONB,
    
    -- 全文検索用（tsvector）
    search_vector tsvector,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 予約テーブル（パーティション対応）
CREATE TABLE room_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid UUID DEFAULT uuid_generate_v4(),
    room_id INTEGER NOT NULL REFERENCES rooms(id),
    guest_id INTEGER NOT NULL REFERENCES guests(id),
    guest_number INTEGER NOT NULL DEFAULT 1,
    is_paid BOOLEAN DEFAULT false,
    
    -- 予約期間（range型）
    stay_period tstzrange NOT NULL,
    
    reserved_at TIMESTAMP WITH TIME ZONE NOT NULL,
    canceled_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    total_amount DECIMAL(10, 2),
    special_requests TEXT,
    
    -- 動的メタデータ（JSONB）
    metadata JSONB DEFAULT '{}',
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- 除外制約（同じ部屋の期間重複を防ぐ）
    EXCLUDE USING gist (room_id WITH =, stay_period WITH &&)
    WHERE (canceled_at IS NULL)
) PARTITION BY RANGE (created_at);

-- パーティション作成（年別分割）
CREATE TABLE room_reservations_2023 PARTITION OF room_reservations
    FOR VALUES FROM ('2023-01-01') TO ('2024-01-01');

CREATE TABLE room_reservations_2024 PARTITION OF room_reservations
    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

CREATE TABLE room_reservations_2025 PARTITION OF room_reservations
    FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');

-- レビューテーブル（全文検索対応）
CREATE TABLE reviews (
    id SERIAL PRIMARY KEY,
    reservation_id BIGINT REFERENCES room_reservations(id),
    rating INTEGER CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    comment_vector tsvector,  -- 全文検索用
    sentiment_score DECIMAL(3, 2),  -- -1.0 to 1.0
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
